version: '3.8'

services:
  sqlserver:
    restart: always 
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
      - MSSQL_BACKUP_DIR=/var/opt/mssql/backup
    ports:
      - "1433:1433"
    volumes:
      - C:\Development\Docker\Volumes\MSSQL\data:/var/opt/mssql/data
      - C:\Development\Docker\Volumes\MSSQL\backup:/var/opt/mssql/backup
      - C:\Development\Docker\Volumes\MSSQL\log:/var/opt/mssql/log
      - C:\Development\Docker\Volumes\MSSQL\secrets:/var/opt/mssql/secrets
  seq:
    restart: always 
    container_name: seq
    image: datalust/seq:latest
    mem_limit: 1GB
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    volumes:
      - C:\Development\Docker\Volumes\SEQ\data:/data
  cosmosdb:
    restart: unless-stopped
    container_name: cosmosdb
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    mem_limit: 2GB
    environment: 
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
    ports:
      - "8081:8081" 
      - "10251:10251" 
      - "10252:10252" 
      - "10253:10253" 
      - "10254:10254"